### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by coderschoolreview** [nnquy/prework-swift#1]
Thank you for your Swift submission,! Quy Nguyen
😋 Everything looks good with the format of your submission. We'll be reviewing your submission soon!

**Comment by imnnquy** [comment]
Thanks for you response :+1:

**Comment by coderschoolreview** [comment]
👍 Congratulation on finishing the Tip Calculator. Here are some quick comments about your prework:

**Tip View:**
- Good usage of `UserDefaults`. This is one of the methods to pass the data from multiple viewController. We will learn few more ways to do that. 
- You shouldn't let the user enter invalid number, should you? I can enter bunch of leading zeros and decimal points. 
- The currency ($) is need in UITextfield. You can also set the `Placeholder` text.
- User can also input decimal number (69.99 $). Right now you just allow integer number only. (You can try `Decimal Pad` for Textfield Control in KeyboardType)

**Setting View:**
- What does the Initial Amount feature do for enhancing user experiences?

**Improvement**
- What if I want to set the percentage tips to 30% or 35%...... You can try different approach for the input: Min, Medium and Max percentage.
- Try to implement animation 
- You can save the last five bill amount and display in Tip View for later look up.
- You can enhance the UI in order to make your app more attractive.

I encourage you to try out the optional tasks to increase your chance. FYI, the deadline was extended to Oct 4rd.

Regards,
CoderSchool

**Comment by imnnquy** [comment]
Thanks for your feedback.
I'll try to improve the App follow your comment, it's really helpful.
